#!/usr/bin/env python

from pywebdriver import app, config, drivers

def main():
    host = config.get('flask', 'host', fallback="0.0.0.0")
    port = config.getint('flask', 'port', fallback=3000)
    debug = config.getboolean('flask', 'debug', fallback=False)
    use_reloader = config.getboolean('flask', 'use_reloader', fallback=False)
    if config.getboolean('application', 'print_status_start'):
        if 'escpos' in drivers:
            drivers['escpos'].push_task('printstatus')
    app.run(host=host, port=port, debug=debug, use_reloader=use_reloader)

# Run application
if __name__ == '__main__':
    main()
